### ISSUE TITLE
License on sample images?

### ISSUE THREAD

**Issue by drewnoakes** [bvibber/hdrfix#13]
Hello!

I maintain a library that pulls metadata from media files and am looking for some XHR sample files to include in this repo, which we use for regression and performance testing:

https://github.com/drewnoakes/metadata-extractor-images

Seems like you have a nice set here. Would it be ok to copy them into the above repo? I would link their source here in the commit message.

**Comment by brion** [comment]
Oh fun! I'll take a look at that when I have a chance. You can consider them under the same license as the program ("MIT" style, so free-to-reuse-or-make-derivs-but-keep-attribution)

**Comment by drewnoakes** [comment]
Thanks Brooke! I've copied them over and given attribution in the commit message 🙏

https://github.com/drewnoakes/metadata-extractor-images/commit/9f7aaa60e99775600226a4832a0049880d55c15e
